services:
  - type: web
    name: krowiczat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"

gunicorn -k eventlet -w 1 app:app --bind 0.0.0.0:$PORT
